name: Build ScreenReader

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish ScreenReader.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=false

      - name: Find published files
        shell: pwsh
        run: |
          Write-Host "Published files:"
          Get-ChildItem -Path . -Recurse -Directory -Filter publish |
            ForEach-Object {
              Write-Host $_.FullName
              Get-ChildItem $_.FullName
            }

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: ScreenReader
          path: '**/publish/**'
          if-no-files-found: error
